---
resources:
  - name: git
    type: git
    source:
      uri: https://github.com/kkalugerov/ConcourseCI
      branch: main

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: git
        trigger: true
      - task: hello-world
        file: git/task-hello-world/task_hello_world.yml
