---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
  - name: resource-src
    # path: resource-src/job-inputs/

params:
  test_env: ((test_env))
run:
  path: echo
  args: [((test_env))]
  # path: resource-src/scripts/bash/echo.sh
