---
platform: linux

image_resource:
  type: docker-image
  source: {repository: alpine}

inputs:
  - name: resource-src
    # path: resource-src/job-inputs/

params:
  test_env: ((test_env))
run:
  path: resource-src/scripts/bash/echo.sh ((test_env))
