---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
  - name: source

## invoke parameter with key test_env from credhub
params:
  test_env: ((test_env))

run:
  args: [((test_env))]
  path: source/scripts/bash/echo.sh
