---
resources:
  - name: resource-src
    type: git
    source:
      uri: https://github.com/kkalugerov/ConcourseCI.git
      branch: main

jobs:
  - name: job-test-app
    public: true
    plan:
      - get: resource-src
        trigger: true
      - task: run-python
        file: resource-src/job-inputs/task-run-python.yml
  
  - name: job-show-date
    plan:
    - get: resource-src
      passed: [job-test-app]
      trigger: true
    - task: show-date
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: sh
          args:
            - -exc
            - date
