---
resources:
  - name: resource-src
    type: git
    source:
      uri: https://github.com/kkalugerov/ConcourseCI.git
      branch: main

jobs:
  - name: job-test-app
    public: true
    plan:
      - get: resource-src
        trigger: true
      - task: run-python
        file: resource-src/job-inputs/run-python.yml
