---
# var_sources:
# - name: test
#   type: dummy
#   config:
#     vars:
#         GIT_REPO: https://github.com/kkalugerov/ConcourseCI.git

resources:
  - name: resource-src
    type: git
    source:
      uri: ((GIT_REPO))
      # uri: ((test:GIT_REPO))
      branch: main


jobs:
  - name: job-test-app
    public: true
    plan:
      - get: resource-src
        trigger: true
      - task: run-python
        file: resource-src/tasks/run_python.yml
  
  - name: job-get-env
    plan:
      - get: resource-src
        passed: [job-test-app]
        trigger: true
      - task: get-env
        file: resource-src/tasks/echo.yml
        # config:
        #   platform: linux
        #   image_resource:
        #     type: docker-image
        #     source: {repository: alpine}
        #   params:
        #     test_env: ((test_env))
        #   run:
        #     path: echo
        #     args: [((test_env))]
