---
resources:
  - name: source
    type: git
    source:
      uri: ((git-repo))
      branch: main

jobs:
  - name: exec_python
    public: true
    plan:
      - get: source
        trigger: true
      - task: exec_python
        file: source/tasks/run_python.yml
  
  - name: exec_bash
    plan:
      - get: source
        passed: [exec_python]
        trigger: true
      - task: run
        file: source/tasks/echo.yml
        # config:
        #   platform: linux
        #   image_resource:
        #     type: docker-image
        #     source: {repository: alpine}
        ##  invoke variable set in credhub with key test_env
        #   params:
        #     test_env: ((test_env))
        #   run:
        #     path: echo
        #     args: [((test_env))]
